"""PromptGym typed models for openenv-core compliance."""

from typing import Dict, Optional
from openenv.core.env_server import Action, Observation, State


class PromptAction(Action):
    """
    The agent's action: a prompt string to be executed against the LLM.
    
    Fields:
        prompt: The prompt text generated by the agent.
                This is what gets evaluated — the quality of this
                prompt determines the reward.
    """
    prompt: str


class PromptObservation(Observation):
    """
    What the agent observes after each step.
    
    Inherits from Observation which already has:
        done: bool
        reward: Optional[float]
        metadata: Dict[str, Any]
    
    Additional fields describe the current task state.
    """
    task_description: str       # What the agent must accomplish
    input_data: str             # The raw input to work with
    task_type: str              # "summarization" | "json_extraction" | "reasoning"
    difficulty: str             # "easy" | "medium" | "hard"
    step: int                   # Current step number (0-indexed)
    max_steps: int              # Maximum steps allowed per episode
    last_llm_output: str = ""   # Output from last step's LLM execution (empty on reset)
    last_score: float = 0.0     # Score from last step (0.0 on reset)
    grader_signals: Dict[str, float] = {}  # Breakdown of scoring signals
    message: str = ""           # Human-readable feedback message


class PromptState(State):
    """
    Full episode metadata.
    
    Inherits from State which already has:
        episode_id: Optional[str]
        step_count: int
    
    Additional fields track episode progress.
    """
    task_id: str = ""
    difficulty: str = "easy"
    total_reward: float = 0.0
    best_reward: float = 0.0
    done: bool = False
    task_description: str = ""
