"""Pydantic v2 schemas for all request/response shapes."""

from pydantic import BaseModel, Field
from typing import Optional, Literal, Dict, Any
from uuid import uuid4


class ResetRequest(BaseModel):
    """Request model for environment reset."""
    difficulty: Literal["easy", "medium", "hard"] = "easy"
    session_id: Optional[str] = None


class StepRequest(BaseModel):
    """Request model for environment step."""
    session_id: str
    action: str = Field(..., min_length=1, description="The prompt generated by the agent")


class Observation(BaseModel):
    """Observation returned after step."""
    task_description: str
    input_data: str
    task_type: str
    step: int
    max_steps: int
    difficulty: str


class StepResponse(BaseModel):
    """Response from environment step."""
    observation: Observation
    reward: float = Field(..., ge=0.0, le=1.0)
    done: bool
    info: Dict[str, Any]


class ResetResponse(BaseModel):
    """Response from environment reset."""
    observation: Observation
    info: Dict[str, Any]
    session_id: str


class StateResponse(BaseModel):
    """Current state of a session."""
    session_id: str
    observation: Observation
    last_reward: float
    total_reward: float
    step: int
    done: bool


class HealthResponse(BaseModel):
    """Health check response."""
    status: str
    llm_mode: str
    version: str = "1.0.0"
